services:
  nginx:
    image: nginx:stable
    container_name: gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nginx

networks:
  nginx:
    external: true
