services:
  #   backend:
  #     image: openjdk:21-jdk-alpine
  #     container_name: backend
  #     ports:
  #       - "3000:3000"
  #     env_file:
  #       - .env
  #     volumes:
  #       - ./back:/app

  #   frotend:
  #     image: nginx:alpine
  #     container_name: frotend
  #     ports:
  #       - "5500:443"
  #     volumes:
  #       - ./front:/usr/share/nginx/html

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

#   redis:
#     image: redis
#     container_name: redis
#     volumes:
#       - redis:/db/redis

#   mongodb:
#     image: mongo
#     container_name: mongodb
#     ports:
#       - "27017:27017"
#     env_file:
#       - .env.mongo
#     volumes:
#       - mongo:/db/mongo

volumes:
  postgres:
#   redis:
#   mongo:
