services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env.postgres.auth
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
