services:
  postgres:
    image: postgres:latest
    container_name: postgres-ecommerce
    restart: unless-stopped
    env_file:
      - .env.postgres.ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
